### ISSUE TITLE
Change API endpoint from `whitelist` to `accesslist`

### ISSUE THREAD

**Issue by tomsaleeba** [tomsaleeba/mongo-atlas-update-whitelist-for-aws#2]
This affects at least https://github.com/tomsaleeba/mongo-atlas-update-whitelist-for-aws/blob/981e794/index.js#L79.

As you can read at the top of [this page](https://docs.atlas.mongodb.com/reference/api/access-lists/):

> This resource replaces the whitelist resource. Atlas deprecated whitelists. The whitelist resource will be disabled in June 2021. Consider updating your applications to use this new resource.

So we need to change 
```diff
- whitelist
+ accessList
```

**Comment by alexpluto** [comment]
@tomsaleeba thanks for this library, very handy!

I was wondering, when were you planning on updating this? Or will someone else be updating it?

Thanks!

**Comment by tomsaleeba** [comment]
@alexpluto I don't have time to update it myself but if you send a PR, I'm happy to accept it.

**Comment by alexpluto** [comment]
@tomsaleeba thank you, I've just submitted a PR now: https://github.com/tomsaleeba/mongo-atlas-update-whitelist-for-aws/pull/3
